version: '3.9'
services: 

  redis:
    extends:
      file: docker/services.yml
      service: redis

  mongo:
    extends:
      file: docker/services.yml
      service: mongo

  nginx:
    extends:
      file: docker/services.yml
      service: nginx
    environment:
      - NGINX_HOST_API=http://host.docker.internal:3079
      - NGINX_HOST_WEB=http://host.docker.internal:3000
    ports:
      - 80:80
    links:
      - redis:redis
      - mongo:mongo