version: '3.9'
services: 

  redis:
    image: redis
    command: --appendonly yes
    volumes:
      - ${DATA_DIR}/redis:/data

  mongo:
    image: mongo
    command: --quiet --logpath /dev/null
    volumes:
      - ${DATA_DIR}/mongodb:/data/db

  api:
    build: ../
    environment:
      - MONGODB_HOST=localhost:27017
      - REDIS_HOST=localhost:6379
      - DATA_DIR=/data
    volumes:
      - ../config:/config
      - ${DATA_DIR}/api:/data

  nginx:
    image: nginx
    logging:
      driver: none
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates