version: '3.9'
services: 

  redis:
    extends:
      file: ../services.yml
      service: redis

  mongo:
    extends:
      file: ../services.yml
      service: mongo

  nginx:
    extends:
      file: ../services.yml
      service: nginx
    environment:
      - NGINX_HOST_API=http://host.docker.internal:3080
      - NGINX_HOST_WEB=http://host.docker.internal:3000
    ports:
      - ${NGINX_EXPOSE}:80
      - ${MONGO_EXPOSE}:27017
      - ${REDIS_EXPOSE}:6379
    links:
      - redis:redis
      - mongo:mongo